-- AlterTable
ALTER TABLE `reporting` ADD COLUMN `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `downloads` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT 'Default Report Name',
    ADD COLUMN `size` VARCHAR(191) NOT NULL DEFAULT '1 MB',
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'completed';
